# Generated by Django 2.2.7 on 2020-02-04 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 11, 9, 49, 202020), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
