# Generated by Django 3.0.2 on 2020-01-29 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='seoText',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='filter',
        ),
        migrations.AddField(
            model_name='item',
            name='filter',
            field=models.ManyToManyField(blank=True, db_index=True, to='item.Filter', verbose_name='Фильтр'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_lower',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 22, 11, 37, 984709), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
