# Generated by Django 2.2.7 on 2020-02-04 15:13

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200204_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AddField(
            model_name='filter',
            name='page_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание страницы'),
        ),
        migrations.AddField(
            model_name='filter',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='filter',
            name='page_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 15, 13, 5, 636377), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
