# Generated by Django 3.0.2 on 2020-01-29 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200129_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 22, 13, 2, 477882), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
