# Generated by Django 3.0.2 on 2020-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200204_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(null=True, verbose_name='Срок действия безлимитного кода'),
        ),
    ]
