# Generated by Django 3.0.2 on 2020-02-04 20:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20200204_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='filter',
            name='page_h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст на странице'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Тескт на странице'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image_small',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='itempart',
            name='name_lower',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itempart',
            name='name_slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True),
        ),
    ]
