# Generated by Django 3.0.2 on 2020-01-29 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20200129_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.CharField(blank=True, max_length=15, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='item',
            name='length',
            field=models.CharField(blank=True, max_length=15, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.CharField(blank=True, max_length=15, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 22, 39, 28, 282005), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
