# Generated by Django 3.0.2 on 2020-01-30 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20200129_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_at_main_menu',
            field=models.BooleanField(default=False, verbose_name='Показывать в главном меню отдельной категорией?'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category',
            field=models.ManyToManyField(blank=True, to='item.Category', verbose_name='Для категорий'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 18, 51, 29, 383008), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
