# Generated by Django 2.2.7 on 2020-01-31 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20200130_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_img/', verbose_name='Изображение категории 370x150'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='filters', to='item.Category', verbose_name='Для категорий'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(db_index=True, related_name='category', to='item.Category', verbose_name='Состоит в категориях'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.Item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 8, 33, 16, 917636), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
