# Generated by Django 3.0.2 on 2020-02-02 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20200131_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название ')),
                ('name_lower', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='item/part/', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 13, 47, 41, 571114), verbose_name='Срок действия безлимитного кода'),
        ),
        migrations.CreateModel(
            name='ItemParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_flower_count', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Букет')),
                ('item_flower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.ItemPart', verbose_name='Состав')),
            ],
        ),
    ]
