# Generated by Django 3.0.2 on 2020-02-02 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20200202_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemparts',
            old_name='item_flower',
            new_name='item_part',
        ),
        migrations.RenameField(
            model_name='itemparts',
            old_name='item_flower_count',
            new_name='item_part_count',
        ),
        migrations.AlterField(
            model_name='itempart',
            name='image',
            field=models.ImageField(blank=True, upload_to='item/part/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 13, 50, 36, 903866), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
