# Generated by Django 3.0.2 on 2020-02-02 13:58

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20200202_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempart',
            options={'verbose_name': 'Элемент букета', 'verbose_name_plural': 'Элементы букетов'},
        ),
        migrations.AlterModelOptions(
            name='itemparts',
            options={'verbose_name': 'Элемент букета', 'verbose_name_plural': 'Элементы букетов'},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='page_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 13, 58, 34, 34174), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
