# Generated by Django 3.0.2 on 2020-02-02 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_auto_20200202_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 2, 23, 11, 54, 914007), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
