# Generated by Django 3.0.2 on 2020-01-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок отображения')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Картинка (1920x680)')),
                ('is_active', models.BooleanField(default=True)),
                ('text_top', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок 1')),
                ('text_middle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок 2')),
                ('text_bottom', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок 3')),
                ('text_button', models.CharField(blank=True, max_length=10, null=True, verbose_name='Надпись на кнопке')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка с кнопки')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
