# Generated by Django 3.0.2 on 2020-02-02 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20200202_2311'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Покупка в 1 клик',
                'verbose_name_plural': 'Покупки в 1 клик',
            },
        ),
    ]
