# Generated by Django 3.0.2 on 2020-02-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20200209_1505'),
        ('page', '0002_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='ФИО')),
                ('email', models.CharField(blank=True, max_length=20, null=True, verbose_name='EMail')),
                ('text', models.TextField(null=True, verbose_name='Отзыв')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isPublished', models.BooleanField(default=False, verbose_name='Отображается ?')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name='Букет')),
            ],
            options={
                'verbose_name': 'Отзыв о товаре',
                'verbose_name_plural': 'Отзывы о товарах',
            },
        ),
    ]
