# Generated by Django 3.0.2 on 2020-02-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordershipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipping',
            name='isFree',
            field=models.BooleanField(default=False, verbose_name='Бесплатная доставка при заказе от 3000'),
        ),
    ]
