# Generated by Django 3.0.2 on 2020-02-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordershipping_isfree'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipping',
            name='freePrice',
            field=models.IntegerField(default=0, verbose_name='этой суммы заказа'),
        ),
        migrations.AlterField(
            model_name='ordershipping',
            name='isFree',
            field=models.BooleanField(default=False, verbose_name='Бесплатная доставка при заказе от '),
        ),
    ]
