# Generated by Django 2.2.7 on 2020-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200204_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='card_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст открытки'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_phono',
            field=models.BooleanField(default=False, verbose_name='Нужно фото при доставке'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_payd',
            field=models.BooleanField(default=False, verbose_name='Заказ оплачен ?'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон получателя'),
        ),
    ]
