# Generated by Django 3.0.2 on 2020-02-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200205_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sender_email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email отправителя'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО отправителя'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон отправителя'),
        ),
    ]
