# Generated by Django 3.0.2 on 2020-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200206_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_need_phono',
        ),
        migrations.AddField(
            model_name='order',
            name='is_need_photo',
            field=models.BooleanField(default=False, null=True, verbose_name='Нужно фото при доставке'),
        ),
    ]
