# Generated by Django 3.0.2 on 2020-02-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200206_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
    ]
