# Generated by Django 3.0.2 on 2020-02-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_receiver_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sber_orderId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
