# Generated by Django 3.0.2 on 2020-02-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_sber_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Оплата'),
        ),
    ]
